# AWS region
variable "region" {
  default     = "us-east-1"
  description = "AWS Region"
}

variable "availability_zones" {
  type        = list(string)
  description = "Availability Zones"
  default     = ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d", "us-east-1e"]
}

# VPC Name
variable "vpc_name" {
  default     = "Mirth-vpc"
  description = "VPC Name"
}

# VPC CIDR
variable "vpc_cidr" {
  default     = "10.0.0.0/16"
  description = "VPC CIDR"
}

# Public Subnet CIDR
variable "public_subnet_cidrs" {
  type        = list(string)
  description = "Public Subnet CIDR values"
  default     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
}

# Private Subnet CIDR
variable "private_subnet_cidrs" {
  type        = list(string)
  description = "Private Subnet CIDR values"
  default     = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
}

# Security EC2 Group Name
variable "ec2_sg_name" {
  default     = "Mirth-EC2-sg"
  description = "Ec2 Instance Security Group Name"
}

# Application Load Balancer Name
variable "albname" {
  default     = "Mirth-alb"
  description = "Application Load Balancer Name"
}

# Cloud Watch Dashboard Name
variable "cloudwatch_dashboard_name" {
  default     = "Mirth-EC2-Dashboard"
  description = "Cloud Watch Dashboard Name"
}

# Instance Key Pair Name
variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

# Instance ami
variable "ami" {
  default     = "ami-04b70fa74e45c3917"
  description = "ami of vm"
}

# Instance Name
variable "instance_name" {
  default     = "Mirth-Instance"
  description = "Instance Name."
}
# Instance type
variable "instance_type" {
  default     = "t2.micro"
  description = "Instance Type."
}

# Root EBS type
variable "root_ebs_type" {
  default     = "gp3"
  description = "Root EBS Type."
}

# Root EBS Size
variable "root_ebs_size" {
  default     = 30
  description = "Root EBS Size."
}

# Extra EBS type
variable "extra_ebs_type" {
  default     = "gp2"
  description = "Extra EBS Type."
}

# Extra EBS Size
variable "extra_ebs_size" {
  default     = 30
  description = "Extra EBS Size."
}

# S3 Bucket Name
variable "bucket_name" {
  default     = "Mirth-S3"
  description = "S3 Bucket Name"
}

# S3 Bucket Environment
variable "bucket_env" {
  default     = "Dev"
  description = "S3 Bucket Environment"
}

# RDS Port
variable "rds_port" {
  default     = 5432
  description = "RDS port"
}

# RDS Instance Size
variable "rds_db_size" {
  default     = 10
  description = "RDS Instance Size"
}

# RDS DataBase Name
variable "db_name" {
  default     = "mirthdb"
  description = "DataBase Name"
}

# RDS Engine(Type)
variable "db_engine" {
  default     = "postgres"
  description = "Type of RDS"
}

# RDS Engine Version
variable "db_engine_version" {
  default     = "16.1"
  description = "RDS Engine Version"
}

# Name of the RDS instance
variable "db_instance_name" {
  default     = "Mirth-database"
  description = "Name of the RDS instance"
}

# RDS Instance Class
variable "db_instance_class" {
  default     = "db.t3.micro"
  description = "RDS Instance Class"
}

# DataBase User Name
variable "db_username" {
  default     = "mirthdb"
  description = "DataBase Username"
}

# DynamoDB Name
variable "dynamodb_name" {
  default     = "mirthdb"
  description = "DataBase Username"
}

# DynamoDB Environment
variable "dynamodb_env" {
  default     = "Training"
  description = "DynamoDB Environment"
}

# DynamoDB Billing Mode
variable "dynamodb_billing_mode" {
  default     = "PROVISIONED"
  description = "DynamoDB  Billing Mode"
}

resource "random_string" "random" {
  length  = 7
  upper   = false
  special = false
}
